(function(root){
  'use strict';
  const fightRule=(path,fallback)=>root.CAGE_FIGHT_RULES?.number(path,fallback)??fallback;

  function createFightFocusFeature(options){
    const {$,getFight,getState,contacts,clamp,rint,focusTier,showFightStage,saveState,trackEvent,tap,beginPlannedFight}=options;
    function updateDisplay(){const fight=getFight();if(!fight)return;const value=clamp(Math.round(fight.focus||fight.focusBase||80),fightRule('focus.absoluteMinimum',50),fightRule('focus.absoluteMaximum',100)),tier=focusTier(value);fight.focus=value;$('#focusValue').textContent=`${value}%`;$('#liveFocusText').textContent=`${value}% FOCUS · ${tier}`}
    function renderEncounter(){
      const fight=getFight();if(!fight?.focusEncounter)return;updateDisplay();const encounter=fight.focusEncounter,box=$('#focusEncounter');box.className='fight-plan-card focus-encounter';
      if(encounter.type==='quiet'){const minimumGain=fightRule('focus.musicMinimumGain',4),maximumGain=fightRule('focus.musicMaximumGain',10),perfectChance=Math.round(fightRule('focus.musicPerfectFocusProbability',.2)*100),maximumFocus=fightRule('focus.absoluteMaximum',100),meditationMinimum=fightRule('focus.meditationMinimumFocus',92);box.innerHTML=`<span class="focus-kicker">THE LOCKER ROOM IS YOURS</span><h2>HOW DO YOU PREPARE?</h2><p>No interruptions. Choose how to use the final minutes before the walkout.</p><div class="focus-options"><div class="focus-option"><button class="focus-choice risk" data-focus-choice="music"><b>LISTEN TO MUSIC</b></button><small class="focus-option-hint">Gain ${minimumGain}–${maximumGain} Focus · ${perfectChance}% chance to hit ${maximumFocus}%</small></div><div class="focus-option"><button class="focus-choice safe" data-focus-choice="meditate"><b>MEDITATE</b></button><small class="focus-option-hint">Reliable · raises Focus to at least ${meditationMinimum}%</small></div></div>`}
      else{const message=encounter.message,contact=message.contact;box.innerHTML=`<span class="focus-kicker">TEXT FROM ${contact.name}</span><h2>INCOMING TEXT</h2><div class="focus-phone"><div class="focus-contact"><img src="${contact.avatar}" alt=""><div><b>${contact.name}</b><small>just now</small></div></div><div class="focus-notification"><b>New message</b><span>Read it now or protect your routine.</span></div></div><div class="focus-options"><div class="focus-option"><button class="focus-choice safe" data-focus-choice="read"><b>READ IT</b></button><small class="focus-option-hint">Open the message · outcome unknown</small></div><div class="focus-option"><button class="focus-choice risk" data-focus-choice="ignore"><b>IGNORE</b></button><small class="focus-option-hint">Leave it unread · ${contact.ignoreDelta} Focus</small></div></div>`}
    }
    function messages(){return (contacts||[]).flatMap(contact=>contact.messages.map(message=>Object.assign({contact},message)))}
    function draw(all){const state=getState(),byId=new Map(all.map(message=>[message.id,message]));let deck=Array.isArray(state.focusTextDeck)?state.focusTextDeck.filter(id=>byId.has(id)):[];if(!deck.length){deck=all.map(message=>message.id);for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}if(deck.length>1&&deck[deck.length-1]===state.lastFocusTextId){const swap=deck.findIndex(id=>id!==state.lastFocusTextId);[deck[swap],deck[deck.length-1]]=[deck[deck.length-1],deck[swap]]}}const id=deck.pop();state.focusTextDeck=deck;state.lastFocusTextId=id;return byId.get(id)||all[0]}
    function begin(){const fight=getFight();if(!fight)return;fight.focusBase=rint(fightRule('focus.startingMinimum',75),fightRule('focus.startingMaximum',90));fight.focus=fight.focusBase;fight.focusResult=null;const all=messages(),quiet=Math.random()<.5||!all.length;fight.focusEncounter=quiet?{type:'quiet'}:{type:'text',message:draw(all)};saveState();showFightStage('focusStage');renderEncounter();trackEvent('fight_focus_presented',{fight_mode:fight.mode,encounter_type:quiet?'quiet':'text',event_id:fight.focusEncounter.message?.id||'routine',contact_id:fight.focusEncounter.message?.contact?.id||'none',starting_focus:fight.focusBase})}
    function resolve(choice){
      const fight=getFight();if(!fight?.focusEncounter||fight.focusResult)return;const before=fight.focus,encounter=fight.focusEncounter;let text='',outcomeType='steady';
      if(encounter.type==='quiet'){if(choice==='music'){if(Math.random()<fightRule('focus.musicPerfectFocusProbability',.2)){fight.focus=fightRule('focus.absoluteMaximum',100);text='The perfect song hits at the perfect moment. Every doubt disappears.';outcomeType='perfect'}else{fight.focus+=rint(fightRule('focus.musicMinimumGain',4),fightRule('focus.musicMaximumGain',10));text='The music raises the pulse and pulls your attention toward the cage.';outcomeType='boost'}}else if(choice==='meditate'){fight.focus=Math.max(fight.focus,fightRule('focus.meditationMinimumFocus',92));text='Your breathing slows. The noise outside the room loses its grip.';outcomeType='steady'}else return}
      else{const message=encounter.message,contact=message.contact;if(choice==='read'){fight.focus=message.focus??(message.minimum?Math.max(fight.focus,message.minimum):fight.focus+(message.delta||0));text=message.text;outcomeType=fight.focus>=before?'boost':'hit'}else if(choice==='ignore'){fight.focus+=contact.ignoreDelta;text=contact.ignoreText;outcomeType='doubt'}else return}
      fight.focus=clamp(Math.round(fight.focus),fightRule('focus.absoluteMinimum',50),fightRule('focus.absoluteMaximum',100));fight.focusResult={choice,before,after:fight.focus,text,outcomeType};updateDisplay();const delta=fight.focus-before,box=$('#focusEncounter'),message=encounter.message,contact=message?.contact,resultTitle=encounter.type==='quiet'?(choice==='music'?'THE MUSIC HITS':'YOUR MIND SETTLES'):(choice==='read'?'MESSAGE OPENED':'MESSAGE LEFT UNREAD'),deltaText=`${delta>0?'+':''}${delta}`,resultCopy=encounter.type==='text'&&choice==='read'?`<div class="focus-thread focus-opened-thread"><div class="focus-contact"><img src="${contact.avatar}" alt=""><div><b>${contact.name}</b><small>just now</small></div></div><div class="focus-text-bubble">${text}</div></div>`:`<p class="focus-result-description">${text}</p>`;box.classList.add(delta<0?'outcome-negative':'outcome-positive');box.innerHTML=`<div class="focus-result"><span class="focus-kicker">LOCKER ROOM · FINAL PREPARATION</span><h2>${resultTitle}</h2>${resultCopy}<div class="focus-score-block"><strong class="focus-result-tier">${focusTier(fight.focus)}</strong><div class="focus-final-score"><b>${fight.focus}% FOCUS</b><span class="focus-delta ${delta<0?'loss':delta===0?'steady':''}">${deltaText}</span></div></div><button class="focus-continue" data-focus-continue type="button">WALK TO THE CAGE</button></div>`;trackEvent('fight_focus_resolved',{fight_mode:fight.mode,encounter_type:encounter.type,event_id:message?.id||'routine',contact_id:contact?.id||'none',choice,starting_focus:before,final_focus:fight.focus,focus_tier:focusTier(fight.focus).toLowerCase().replace(/\s+/g,'_')});tap();saveState();
    }
    function continueAfter(){const fight=getFight();if(!fight?.focusResult)return;showFightStage('liveStage');beginPlannedFight();tap()}
    return {updateDisplay,renderEncounter,messages,draw,begin,resolve,continueAfter};
  }

  root.CAGE_FIGHT_FOCUS={createFightFocusFeature};
})(globalThis);
