-- Fifteen additional CPU fighters, one per level 2-16, using portraits 51-65.
-- Requires 20260908150000_expand_fighter_avatars_to_65.sql.
-- Attributes follow the current generated-opponent curve and avatar allocations.
-- Background histories are synthetic seed data with unknown opponent ranks;
-- modest quality (30-40) avoids seeding an artificial elite resume.
-- Inserts directly into the existing RLS-protected table; no staging table.
begin;
do $$
declare seed record;
begin
 for seed in
  select * from (values
('ca6e0000-0000-4000-8000-000000020003'::uuid,'IronCometPHX','phoenix','striker','fighter-51',2,2,1,8,5,4,3,8,6,4,3,'[{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000030003'::uuid,'SilverJackalLAX','los-angeles','grappler','fighter-52',3,8,3,5,8,4,3,5,8,7,7,'[{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000040003'::uuid,'HarborAnvilBWI','baltimore','striker','fighter-53',4,12,6,4,3,8,5,8,8,8,6,'[{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000050003'::uuid,'CopperViperMIA','miami','grappler','fighter-54',5,16,10,3,4,5,8,7,7,9,10,'[{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000060003'::uuid,'DesertTempestLV','las-vegas','striker','fighter-55',6,19,4,6,5,5,4,11,11,9,8,'[{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000070003'::uuid,'SteelUndertowBOS','boston','grappler','fighter-56',7,23,8,7,3,6,4,10,9,12,11,'[{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000080003'::uuid,'MidnightFalconNYC','new-york','striker','fighter-57',8,31,16,4,7,5,4,13,14,11,11,'[{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000090003'::uuid,'GraniteHawkDEN','denver','grappler','fighter-58',9,36,23,5,4,7,4,12,12,15,14,'[{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000100003'::uuid,'NeonThunderSEA','seattle','striker','fighter-59',10,37,7,4,5,4,7,15,15,13,14,'[{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000110003'::uuid,'CrimsonCurrentHOU','houston','grappler','fighter-60',11,43,15,6,4,4,6,15,14,16,17,'[{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000120003'::uuid,'GoldenMaulerCHI','chicago','striker','fighter-61',12,50,25,7,5,3,5,19,18,15,16,'[{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000130003'::uuid,'PacificPhantomSF','san-francisco','grappler','fighter-62',13,57,37,3,7,4,6,17,18,19,20,'[{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000140003'::uuid,'BayouSentinelNOLA','new-orleans','striker','fighter-63',14,60,12,5,3,7,5,21,20,20,19,'[{"outcome":"loss","won":false,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000150003'::uuid,'EmeraldCyclonePDX','portland','grappler','fighter-64',15,66,23,5,4,3,8,20,20,22,23,'[{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb),
    ('ca6e0000-0000-4000-8000-000000160003'::uuid,'AtlanticOnyxATL','atlanta','striker','fighter-65',16,72,36,4,6,6,4,23,24,22,21,'[{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"loss","won":false,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":30,"quality_points":30,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":35,"quality_points":35,"opponent_rank_at_booking":null,"opponent_level_at_booking":null},{"outcome":"win","won":true,"quality":40,"quality_points":40,"opponent_rank_at_booking":null,"opponent_level_at_booking":null}]'::jsonb)
  ) as seed_data (id,handle,city,archetype,fighter_avatar,level,wins,losses,
  base_power,base_speed,base_chin,base_cardio,power,speed,chin,cardio,ranking_history)
 loop
  -- Re-running must never reset records, history, stats, or activation status.
  if exists(select 1 from public.cage_seed_fighters existing where existing.id=seed.id) then
   continue;
  end if;
  -- Any collision aborts the entire batch, including earlier loop inserts.
  if exists(select 1 from public.cage_profiles profile where lower(profile.handle)=lower(seed.handle))
   or exists(select 1 from public.cage_name_registry registry where lower(registry.name)=lower(seed.handle)) then
   raise exception 'An additional seeded fighter handle conflicts with a reserved player name';
  end if;
  insert into public.cage_seed_fighters (id,handle,city,archetype,fighter_avatar,level,wins,losses,
  base_power,base_speed,base_chin,base_cardio,power,speed,chin,cardio,ranking_history)
  values (seed.id,seed.handle,seed.city,seed.archetype,seed.fighter_avatar,seed.level,seed.wins,seed.losses,seed.base_power,seed.base_speed,seed.base_chin,seed.base_cardio,seed.power,seed.speed,seed.chin,seed.cardio,seed.ranking_history)
  on conflict (id) do nothing;
 end loop;
end $$;
commit;
